[package]
name = "ZeroG"
version = "1.0.0"
authors = ["Team ZeroG"]

[addresses]
zerog = "0x40e2eb967aa9abb469a5d3437717560c9b77b5af2f27f99c039a7c90c0bfc42d"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework" }


